import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
        <meta charSet="utf-8"/>
        <link rel="icon" href="/favicon.ico"/>
        <title>MBTI별 좋아하는 컬러</title>
        <link rel="stylesheet" as="style" crossOrigin={''} href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.6/dist/web/static/pretendard.css"/>
      </head>
      <body className={inter.className}>{children}</body>
      </html>
  );
}
